In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import joblib

In [11]:
products_path = "../data/raw/amazon_products.csv"
categories_path = "../data/raw/amazon_categories.csv"

In [12]:
products_sample = pd.read_csv(products_path,nrows=5)

categories_sample = pd.read_csv(categories_path, nrows=5)

In [13]:
products_sample.head()

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,104,False,2000
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://m.media-amazon.com/images/I/81bQlm7vf6...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,104,False,1000
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://m.media-amazon.com/images/I/71EA35zvJB...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,104,False,300
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://m.media-amazon.com/images/I/91k6NYLQyI...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,104,False,400
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://m.media-amazon.com/images/I/61NJoaZcP9...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,104,False,400

In [14]:
categories_sample.head()

   id                     category_name
0   1          Beading & Jewelry Making
1   2                 Fabric Decorating
2   3       Knitting & Crochet Supplies
3   4              Printmaking Supplies
4   5  Scrapbooking & Stamping Supplies

In [15]:
products_sample.columns.tolist()

['asin',
 'title',
 'imgUrl',
 'productURL',
 'stars',
 'reviews',
 'price',
 'listPrice',
 'category_id',
 'isBestSeller',
 'boughtInLastMonth']

In [16]:
categories_sample.columns.tolist()

['id', 'category_name']

In [17]:
products_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   asin               5 non-null      str
 1   title              5 non-null      str
 2   imgUrl             5 non-null      str
 3   productURL         5 non-null      str
 4   stars              5 non-null      float64
 5   reviews            5 non-null      int64
 6   price              5 non-null      float64
 7   listPrice          5 non-null      float64
 8   category_id        5 non-null      int64
 9   isBestSeller       5 non-null      bool
 10  boughtInLastMonth  5 non-null      int64
dtypes: bool(1), float64(3), int64(3), str(4)
memory usage: 1.5 KB

In [18]:
categories_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             5 non-null      int64
 1   category_name  5 non-null      str
dtypes: int64(1), str(1)
memory usage: 332.0 bytes

In [27]:
categories = pd.read_csv(categories_path)

In [31]:
categories.shape

(248, 2)

In [30]:
print("Number of categories:", categories['id'].nunique())

Number of categories: 248

In [32]:
categories.head()

   id                     category_name
0   1          Beading & Jewelry Making
1   2                 Fabric Decorating
2   3       Knitting & Crochet Supplies
3   4              Printmaking Supplies
4   5  Scrapbooking & Stamping Supplies

In [19]:
print(products_sample[['asin','category_id']])

         asin  category_id
0  B014TMV5YE          104
1  B07GDLCQXV          104
2  B07XSCCZYG          104
3  B08MVFKGJM          104
4  B01DJLKZBA          104

In [33]:
print(categories_sample[['id','category_name']].head())

   id                     category_name
0   1          Beading & Jewelry Making
1   2                 Fabric Decorating
2   3       Knitting & Crochet Supplies
3   4              Printmaking Supplies
4   5  Scrapbooking & Stamping Supplies

In [34]:
print(products_sample['category_id'].dtype)
print(categories_sample['id'].dtype)

int64
int64

In [37]:
common_ids = set(products_sample['category_id']) & set(categories['id'])

print("Common IDs:", common_ids)
print("Number of common IDs:", len(common_ids))

Common IDs: {104}
Number of common IDs: 1

In [25]:
categories_sample['id'].nunique()

5

In [36]:
merged_sample = products_sample.merge(
    categories,
    left_on='category_id',
    right_on='id',
    how='left'
)

print(merged_sample[['asin', 'category_id', 'category_name']])

         asin  category_id category_name
0  B014TMV5YE          104     Suitcases
1  B07GDLCQXV          104     Suitcases
2  B07XSCCZYG          104     Suitcases
3  B08MVFKGJM          104     Suitcases
4  B01DJLKZBA          104     Suitcases

In [38]:
df = pd.read_csv(
    products_path,
    nrows=100000
)

In [39]:
df.shape

(100000, 11)

In [40]:
df.head()

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,104,False,2000
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://m.media-amazon.com/images/I/81bQlm7vf6...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,104,False,1000
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://m.media-amazon.com/images/I/71EA35zvJB...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,104,False,300
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://m.media-amazon.com/images/I/91k6NYLQyI...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,104,False,400
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://m.media-amazon.com/images/I/61NJoaZcP9...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,104,False,400

In [41]:
df.tail()

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
99995,B09XFK69N3,Run DMC Fleece Pullover Sweatshirt Little Kid ...,https://m.media-amazon.com/images/I/61M5WV47Bd...,https://www.amazon.com/dp/B09XFK69N3,4.6,46,19.19,0.0,84,False,0
99996,B0C1FB8393,Boys' USA Catboats Long-Sleeve Harbor Performa...,https://m.media-amazon.com/images/I/619-PvshJj...,https://www.amazon.com/dp/B0C1FB8393,5.0,1,32.88,42.0,84,False,0
99997,B09GC97655,Monster Jam Boys' Dragon Zombie Grave Digger M...,https://m.media-amazon.com/images/I/81AA3uv1ni...,https://www.amazon.com/dp/B09GC97655,4.4,13,16.95,0.0,84,False,0
99998,B01GS70WYC,Toddler Boy Pull on Jeans Baby Denim Pants B103,https://m.media-amazon.com/images/I/81FkP32jWh...,https://www.amazon.com/dp/B01GS70WYC,4.6,258,18.99,0.0,84,False,0
99999,B075XHHWXT,Boys Girls Ultralight Puffer Down Jacket Stand...,https://m.media-amazon.com/images/I/71F9FjK0fb...,https://www.amazon.com/dp/B075XHHWXT,0.0,0,24.99,0.0,84,False,0

In [42]:
df.shape

(100000, 11)

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   asin               100000 non-null  str
 1   title              100000 non-null  str
 2   imgUrl             100000 non-null  str
 3   productURL         100000 non-null  str
 4   stars              100000 non-null  float64
 5   reviews            100000 non-null  int64
 6   price              100000 non-null  float64
 7   listPrice          100000 non-null  float64
 8   category_id        100000 non-null  int64
 9   isBestSeller       100000 non-null  bool
 10  boughtInLastMonth  100000 non-null  int64
dtypes: bool(1), float64(3), int64(3), str(4)
memory usage: 26.4 MB

In [44]:
df.describe(include="all")

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
count,100000,100000,100000,100000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000,100000.000000
unique,100000,96439,96308,100000,NaN,NaN,NaN,NaN,NaN,2,NaN
top,B014TMV5YE,Men's Ultraboost 23 Running Shoe,https://m.media-amazon.com/images/I/71u96R-Cb1...,https://www.amazon.com/dp/B014TMV5YE,NaN,NaN,NaN,NaN,NaN,False,NaN
freq,1,81,38,1,NaN,NaN,NaN,NaN,NaN,99626,NaN
mean,NaN,NaN,NaN,NaN,4.078889,470.320500,48.397080,18.057276,118.819380,NaN,33.313000
std,NaN,NaN,NaN,NaN,1.191573,2878.566625,73.609606,48.913972,51.827728,NaN,193.861084
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,69.000000,NaN,0.000000
25%,NaN,NaN,NaN,NaN,4.100000,0.000000,16.990000,0.000000,91.000000,NaN,0.000000
50%,NaN,NaN,NaN,NaN,4.400000,0.000000,26.990000,0.000000,110.000000,NaN,0.000000
75%,NaN,NaN,NaN,NaN,4.600000,128.000000,50.380000,14.990000,114.000000,NaN,0.000000
max,NaN,NaN,NaN,NaN,5.000000,292474.000000,4999.000000,999.990000,253.000000,NaN,10000.000000

In [45]:
df.isna().sum()

asin                 0
title                0
imgUrl               0
productURL           0
stars                0
reviews              0
price                0
listPrice            0
category_id          0
isBestSeller         0
boughtInLastMonth    0
dtype: int64

In [46]:
df.duplicated().sum()

np.int64(0)